---

- name: "Check for configuration directory: {{ config_dir }}"
  delegate_to: localhost
  ansible.builtin.stat:
    path: "{{ config_dir }}"
  register: _host_config

- name: "Copy configuration files: {{ config_dir | basename }}"
  ansible.builtin.copy:
    src: "{{ config_dir }}/"
    dest: "{{ docker_project_path }}/{{ config_dir | basename }}/"
    directory_mode : '0755'
    mode:            '0644'
  register: _copy
  when:
    - _host_config.stat.exists
    - _host_config.stat.isdir
  notify: Restart Pi-hole
