---

## Init

- name: Ensure project directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ docker_project_path }}"
    - "{{ docker_project_path }}/etc-pihole"
  tags: ["init"]

## Configure

- name: Generate web password file
  ansible.builtin.copy:
    content: "{{ pihole_webpassword }}"
    dest: "{{ docker_project_path }}/pihole_password"
    mode: '0600'
  no_log: true

- name: Template docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ docker_project_path }}/docker-compose.yml"
    mode: '0644'
    validate: "{{ docker_cmd }} compose -f %s config"
    backup: true

- name: Initialize adlists
  ansible.builtin.include_tasks: _init_adlists.yml
  tags: ["configure", "configure-adlists"]

## Run

- name: Start app
  ansible.builtin.include_role: { name: djuuu.docker_project, tasks_from: compose-up }
  tags: ["start"]

## Post-configure

- name: Configure custom DNS and CNAME records
  ansible.builtin.include_tasks: tasks/configure-dns.yml
  tags: ["configure", "configure-dns"]
  when: (pihole_dns_hosts        | length > 0)
     or (pihole_dns_cnameRecords | length > 0)
